from app import create_app
from app.models import Employee
from app import db

# Initialize the app
app = create_app()

def add_user():
    email = input('Enter email: ').strip()
    emp_name = input('Enter employee name: ').strip()
    password = input('Enter password: ').strip()
    role = (input('Enter role (admin/employee/manager) [employee]: ').strip() or 'employee').lower()

    # Check if user already exists
    existing = Employee.query.filter_by(email=email).first()
    if existing:
        print('User already exists!')
        return

    # If creating an employee, allow assigning a manager (optional)
    manager_id = None
    if role == 'employee':
        managers = Employee.query.filter(Employee.role.ilike('manager')).all()
        if managers:
            print('Available managers:')
            for m in managers:
                print(f"{getattr(m,'emp_id',None)} - {m.emp_name} ({m.email})")
            manager_input = input('Enter manager emp_id to assign (leave blank for none): ').strip()
            if manager_input:
                manager_id = manager_input

    # Ensure emp_id is set. The Employee.emp_id column is the primary key
    # and may not be automatically generated by the DB. Generate a new
    # numeric emp_id by taking the max existing numeric emp_id + 1. If
    # none exist, fall back to 1001.
    new_emp_id = None
    try:
        existing_ids = [e.emp_id for e in Employee.query.with_entities(Employee.emp_id).all()]
        numeric_ids = [int(i) for i in existing_ids if i and str(i).isdigit()]
        if numeric_ids:
            new_emp_id = str(max(numeric_ids) + 1)
        else:
            new_emp_id = '1001'
    except Exception:
        # if anything goes wrong, use a UUID-like fallback
        import uuid
        new_emp_id = str(uuid.uuid4())

    user = Employee(emp_id=new_emp_id, email=email, emp_name=emp_name, role=role, manager_id=manager_id)
    user.set_password(password)
    db.session.add(user)
    try:
        db.session.commit()
        print(f'User {email} created successfully!')
    except Exception as e:
        db.session.rollback()
        print('Failed to create user:', e)


def list_users():
    users = Employee.query.all()
    if not users:
        print('No users found.')
        return
    print(f"{'emp_id':<30} {'emp_name':<25} {'email':<35} {'role':<10}")
    print('-' * 100)
    for u in users:
        print(f"{getattr(u, 'emp_id', ''):<30} {getattr(u, 'emp_name', ''):<25} {getattr(u, 'email', ''):<35} {getattr(u, 'role', ''):<10}")


if __name__ == '__main__':
    with app.app_context():
        while True:
            print('\nSelect an option:')
            print('1) Add user')
            print('2) List users')
            print('3) Exit')
            choice = input('Choice: ').strip()
            if choice == '1':
                add_user()
            elif choice == '2':
                list_users()
            elif choice == '3':
                break
            else:
                print('Invalid choice.')
